### ISSUE TITLE
Web: drug pages with nothing on them

### ISSUE THREAD

**Issue by ntatonetti** [tatonetti-lab/onsides#16]
There are some bags for drugs that don't have any adverse effects. Investigate why and let's discuss if they should be removed from or if the data can be found.

E.g. https://onsides.tatonettilab.org/drugs/1315411

**Comment by dhvanim** [comment]
These drugs only have labels that are part of kits (which we chose to not display). I can think more on whether to remove them and do some more digging again to see if i can find some data to display for them
