### ISSUE TITLE
Automate Rebuild

### ISSUE THREAD

**Issue by cthoyt** [tatonetti-lab/onsides#3]
It would be really important to have a single command that completely rebuilds the database from scratch and outputs artifacts to a desired location. Right now #2 points out that it's not super obvious in what order to run each of the python scripts. After doing #1, it would be possible to make a single command that could be run like `python -m onsides`. This could be further wrapped with a tool like `tox` that takes care of creating clean virtual environments, installation, and running the code in a standardized way.

How memory/time intensive is building this database? I think GitHub Actions allows for jobs that last up to 24 hours with something like 16gb of RAM. If the database could be built under these constraints, then it could be completely run in an automated way on a cron job and automatically release the results without any human/manual steps

**Comment by ntatonetti** [comment]
- Added a significant amount of documentation on the database generation in DATABASE.md. 
- Added SPL Processor (spl_processor.py) to manage the download of SPLs from DailyMed
- Added new Deployment Tracker (deployment_tracker.py) to manage the process of regenerating the database and managing updates. 
- Added releases.json to track release meta data
