### ISSUE TITLE
Commit results into version control

### ISSUE THREAD

**Issue by cthoyt** [tatonetti-lab/onsides#5]
It looks like the database build is less than 100mb, which means it can be directly committed into version control (or alternatively, uploaded with the tag/release on GitHub. This is much more sustainable than using a lab website, which could stop existing without notice

Additionally, there are third party tools like Zenodo that can host data. You can either upload data there directly or integrate with GitHub to create archival records any time you make a release on GitHub

**Comment by ntatonetti** [comment]
Moved the data downloads to the release.

**Comment by cthoyt** [comment]
Would also suggest not including version information in the names of the files, since they can be accessed via a versioned tag now, and it's not obvious how to programmatically generate the file name based on the version atm

Further, I'd suggest go strictly with date-based versioning for the tags
